### ISSUE TITLE
when resource doesn't have any items in depend on it throws 404

### ISSUE THREAD

**Issue by Saifallak** [webparking/nova-belongs-to-dependency#4] opened 2022-03-25 00:43 UTC
ex:

- belongsto Category
- dependonbelongsto book

if category doesn't have any books, it throws 404

**Comment by RVxLab** [comment] 2022-05-28 23:50
Sorry for the late response on this. Does this still happen in Nova 4?

**Comment by Saifallak** [comment] 2022-05-29 08:12
Idk, I don’t use nova 4 at all

**Comment by RVxLab** [comment] 2022-05-31 20:57
@dgerrese @remkobrenters Can one of you take a look at this?

@Saifallak Can you provide a minimal example to help reproduce this issue? A private repo would be best.

**Comment by Saifallak** [comment] 2022-05-31 21:22
Sorry, i don't have nova lic. Anymore, so can't do it

**Comment by remkobrenters** [comment] 2022-06-01 07:54
@dgerrese can you schedule this one to take a look?

**Comment by dgerrese** [comment] 2022-06-01 08:02
@remkobrenters I'll have a look later this week.

**Comment by dgerrese** [comment] 2022-06-07 09:06
@remkobrenters Unfortunately, I could not reproduce this.

Until we have a way to reproduce this, I will close this issue.

If anyone can provide steps to reproduce this issue, please feel free to open a new bug report.

**Closed as not planned by dgerrese** 2022-06-07 09:06 UTC
